install:
  - xelatex Pinglei_Guo_Resume.tex
  - xelatex Pinglei_Guo_Resume.cn.tex
  # for backwards compatibility
  - cp Pinglei_Guo_Resume.pdf at15.en.pdf
scripts:
  build: xelatex at15.en.tex
  awesome-cv: xelatex resume.tex
  # TODO: this is not working, due to Ayi split them?
  clean:
    - sh -c "rm *.aux *.out *.log"
